spring.application.name=API-Gateway

server.port = 8899

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Route to Customer Microservice using Eureka service discovery
spring.cloud.gateway.server.webflux.routes[0].id=CustomerMicroservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CUSTOMER
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/customer/**

# Route to Document Microservice using Eureka service discovery
spring.cloud.gateway.server.webflux.routes[1].id=DocumentMicroservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DOCUMENTS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/documents/**

# Route to Regional Head Microservice using Eureka service discovery
spring.cloud.gateway.server.webflux.routes[2].id=RegionalHeadMicroservice
spring.cloud.gateway.server.webflux.routes[2].uri=lb://REGIONALHEAD
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/head/**

spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/customer/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/customer/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/customer/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/customer/**].allowCredentials=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/documents/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/documents/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/documents/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/documents/**].allowCredentials=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/head/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/head/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/head/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/head/**].allowCredentials=true

