spring.application.name=Documents

server.port=9096

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=docsdb

logging.level.org.springframework.web=DEBUG

spring.mvc.trailing-slash.matching=true

spring.jackson.default-property-inclusion=always

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
