import React, { useEffect, useState } from "react";
import "./Level2Officer.css";
import { FiEdit } from "react-icons/fi";
import { MdDelete } from "react-icons/md";
import axios from "axios";
const Level2Officer = ({ initialData }) => {
  const [officers, setOfficers] = useState(initialData || []);
  const [error, setError] = useState(null);
  const fetchOfficers = () => {
    axios
      .get("http://localhost:9197/api/users")
      .then((response) => {
        setOfficers(
          response.data.filter((user) => user.role === "Level2Officer")
        );
        setError(null); // clear error, if any
      })
      .catch((error) => {
        setError(error);
      });
  };
  useEffect(() => {
    fetchOfficers();
  }, []);
 
  if (error) return <div>Error Loading Data</div>;
 
  const [form, setForm] = useState({
    _id: "",
    email: "",
    username: "",
    firstName: "",
    lastName: "",
    contactPhone: "",
    role: "",
    createdAt: "",
    lastLoginAt: "",
    status: "",
    associatedPolicyHolderId: "",
    associatedHospitalId: "",
    address: "",
    password: "",
    specialization: "",
    isAvailable: "",
  });
  const [isEditing, setIsEditing] = useState(false);
 
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
 
  const phoneRegex = /^[0-9]{7,15}$/;
 
  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  };
 
  const validateForm = () => {
    if (
      !form.email ||
      !form.firstName ||
      !form.lastName ||
      !form.contactPhone
    ) {
      alert("Please fill in all fields.");
      return false;
    }
    if (!emailRegex.test(form.email)) {
      alert("Please enter a valid email address.");
      return false;
    }
    if (!phoneRegex.test(form.contactPhone)) {
      alert("Please enter a valid phone number (7-15 digits).");
      return false;
    }
    return true;
  };
 
  const handleAdd = async () => {
    if (!validateForm()) return;
 
    const userToAdd = {
      _id: null, // generated by MongoDB usually
      email: form.email,
      username: null,
      role: "Level2Officer",
      firstName: form.firstName,
      lastName: form.lastName,
      contactPhone: form.contactPhone,
      createdAt: new Date().toISOString(),
      lastLoginAt: null,
      status: form.status,
      associatedPolicyHolderId: null,
      associatedHospitalId: null,
      address: null,
      password: form.contactPhone, // default password = phone number
      specialization: null,
      isAvailable: null,
    };
 
    try {
      const response = await axios.post(
        "http://localhost:9197/api/users",
        userToAdd
      );
      fetchOfficers();
      console.log("User added:", response.data);
 
      setForm({
        _id: null,
        email: "",
        firstName: "",
        lastName: "",
        contactPhone: "",
        status: "",
      });
      // update your local state or reset form as needed
    } catch (error) {
      console.error("Error adding user:", error);
    }
  };
 
  const handleEdit = (officer) => {
    setForm(officer);
    setIsEditing(true);
  };
 
  const handleUpdate = () => {
    if (!validateForm()) return;
    console.log(form.email);
    const updateId = officers.filter(
      (officer) => officer.email === form.email
    )[0]._id;
 
    console.log(updateId);
 
    axios
      .put(`http://localhost:9197/api/users/${updateId}`, form)
 
      .then((response) => {
        fetchOfficers();
        console.log("User Updated: " + response.data);
      })
      .catch((error) => {
        console.log("error :" + error);
      });
    setForm({
      id: null,
      email: "",
      firstName: "",
      lastName: "",
      contactPhone: "",
      status: "",
    });
    setIsEditing(false);
  };
 
  const handleDelete = (id) => {
    if (window.confirm("Are you sure you want to delete this officer?")) {
      // setOfficers((prev) => prev.filter((officer) => officer.id !== id));
      console.log(id);
 
      axios
        .delete(`http://localhost:9197/api/users/${id}`)
        .then((response) => {
          fetchOfficers();
          console.log("user deleted " + response.data);
        })
        .catch((error) => {
          console.log("error : " + error);
        });
    }
  };
 
  return (
    <div className="level1">
      <div className="container">
        <h2 className="heading">Level 2 Officers</h2>
 
        <table className="officer-table">
          <thead>
            <tr>
              <th>Email ID</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Phone Number</th>
              <th>Status</th>
              <th>Created On</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {officers.length === 0 ? (
              <tr>
                <td colSpan="5" className="no-data">
                  No officers found.
                </td>
              </tr>
            ) : (
              officers.map((officer) => (
                <tr key={officer.id} className="table-row">
                  <td>{officer.email}</td>
                  <td>{officer.firstName}</td>
                  <td>{officer.lastName}</td>
                  <td>{officer.contactPhone}</td>
                  <td>{officer.status}</td>
                  <td>{officer.createdAt}</td>
                  <td>
                    <button
                      className="btn update-btn"
                      onClick={() => handleEdit(officer)}
                    >
                      <FiEdit />
                    </button>
                    <button
                      className="btn delete-btn"
                      onClick={() => handleDelete(officer._id)}
                    >
                      <MdDelete />
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
 
        <div className="form-container">
          <h3 className="form-heading">
            {isEditing ? "Update Officer" : "Add Officer"}
          </h3>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              isEditing ? handleUpdate() : handleAdd();
            }}
          >
            <div className="form-group">
              <label htmlFor="email" className="form-label">
                Email ID:
              </label>
              <input
                id="email"
                type="email"
                name="email"
                value={form.email}
                onChange={handleChange}
                className="form-input"
                required
                placeholder="example@mail.com"
                disabled={isEditing ? true : false}
              />
            </div>
            <div className="form-group">
              <label htmlFor="firstName" className="form-label">
                First Name:
              </label>
              <input
                id="firstName"
                type="text"
                name="firstName"
                value={form.firstName}
                onChange={handleChange}
                className="form-input"
                required
                placeholder="John"
              />
            </div>
            <div className="form-group">
              <label htmlFor="lastName" className="form-label">
                Last Name:
              </label>
              <input
                id="lastName"
                type="text"
                name="lastName"
                value={form.lastName}
                onChange={handleChange}
                className="form-input"
                required
                placeholder="Doe"
              />
            </div>
            <div className="form-group">
              <label htmlFor="contactPhone" className="form-label">
                Phone Number:
              </label>
              <input
                id="contactPhone"
                type="tel"
                name="contactPhone"
                value={form.contactPhone}
                onChange={handleChange}
                className="form-input"
                required
                placeholder="1234567890"
                pattern="[0-9]{7,15}"
                title="Phone number should be 7 to 15 digits"
              />
            </div>
            <div className="form-group">
              <label htmlFor="status" className="form-label">
                Status :
              </label>
              <input
                id="status"
                type="text"
                name="status"
                value={form.status}
                onChange={handleChange}
                className="form-input"
                required
                placeholder="Active"
              />
            </div>
            <div className="form-buttons">
              <button
                type="submit"
                className={`btn ${isEditing ? "update-btn" : "add-btn"}`}
              >
                {isEditing ? "Update" : "Add"}
              </button>
              {isEditing && (
                <button
                  type="button"
                  className="btn cancel-btn"
                  onClick={() => {
                    setIsEditing(false);
                    setForm({
                      id: null,
                      email: "",
                      firstName: "",
                      lastName: "",
                      phone: "",
                    });
                  }}
                >
                  Cancel
                </button>
              )}
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};
 
export default Level2Officer;